version: '3.5'

services:
  db:
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_DB: fastapi 
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - psql-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: engjat94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: River1993!
    ports:
      - "8080:80"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data


  uikafka:
    container_name: uikafka
    image: provectuslabs/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: true 
    ports:
      - "8081:8080"
    volumes:
      - kafka-ui-config:/config.yml

volumes:
  psql-db:
  zk-data:
  zk-txn-logs:
  kafka-data:
  kafka-ui-config:
